import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

const Terms = () => {
  return (
    <div className="min-h-screen bg-gradient-subtle font-[Inter]">
      <Navigation />
      
      <div className="pt-32 pb-20">
        <div className="container mx-auto px-4 max-w-4xl">
          <h1 className="text-5xl font-bold mb-8 animate-fade-in-up">Terms & Conditions</h1>
          
          <div className="prose prose-lg max-w-none space-y-6 text-muted-foreground animate-fade-in">
            <p className="text-sm text-muted-foreground">Last updated: July 27, 2026</p>
            
            <section>
              <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">1. Acceptance of Terms</h2>
              <p>
                By accessing, browsing, or utilizing the website www.estatenest.ca or engaging the insurance brokerage services of Estate Nest Inc., you acknowledge that you have read, understood, and agree to be legally bound by these Terms and Conditions. If you do not accept these terms in their entirety, you are strictly prohibited from using our website or automated services.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">2. Scope of Services & Provincial Licensing</h2>
              <p>
                Estate Nest Inc. operates as a licensed independent corporate insurance brokerage. We provide professional advice, risk assessment, and policy placement services for products including Life Insurance, Critical Illness Insurance, Disability Insurance, Mortgage Insurance, Travel Insurance, and Segregated Funds.
              </p>
              <p className="mt-4">
                Estate Nest Inc. is explicitly licensed to conduct business only within the provinces of Alberta and Ontario, Canada. Any digital tool, quote generation, or content provided on this website is intended solely for residents of these two jurisdictions.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">3. Quotes, Market Estimates, & Underwriting Approval</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>All premium rates and quotes generated by our automated digital engines, AI systems, or manual broker evaluations are non-binding estimates only.</li>
                <li>Final policy approvals, risk classifications, premium ratings, and eventual policy issuances are exclusively determined by the third-party insurance underwriters, not Estate Nest Inc.</li>
                <li>Quotes are subject to change without notice based on market adjustments, age brackets, medical exam results, or changes to underwriting guidelines.</li>
                <li>Any material misrepresentation, omission, or withholding of medical or lifestyle facts by the client during the quote or application phase will result in the immediate denial of coverage or the voiding of an issued policy.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">4. Client Initiative & Professional Relationship</h2>
              <p>
                You explicitly agree that any submission of data, request for information, or quote inquiry is initiated entirely of your own free will, for your own benefit, and without commercial coercion. No professional broker-client relationship is formally established until a licensed representative of Estate Nest Inc. reviews your case and initiates a formal application track with an insurance underwriter.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">5. AI & Automated Social Media Content Disclaimer</h2>
              <p>
                Estate Nest Inc. utilizes advanced automation, artificial intelligence agents, and smart-queuing technologies (including systems like SureThing.io and Publer) to generate, schedule, and distribute informational content across our social media channels and website blog.
              </p>
              <p className="mt-4">
                While we use reasonable administrative efforts to program strict compliance guardrails, all automated content, posts, and articles are provided purely for general educational and brand awareness purposes. Social media posts do not constitute binding financial, legal, medical, or tailored insurance advice. Users must consult directly with a human licensed broker before making any structural changes to their insurance portfolios.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">6. Acceptable Website Use & Prohibited Acts</h2>
              <p>When interacting with our web systems and online quote forms, you are strictly prohibited from:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Injecting malicious scripts, code, malware, worms, or trojans into form fields.</li>
                <li>Attempting to bypass our Web Application Firewalls (WAF) or gain unauthorized root access to our servers or consumer databases.</li>
                <li>Using automated scrapers, bots, or spiders to extract our proprietary pricing tables, copy, or customer data.</li>
                <li>Submitting fraudulent, fictitious, or stolen identities or health data.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">7. Intellectual Property</h2>
              <p>
                All original copy, web layouts, code architecture, graphic designs, logos, and proprietary data structures on www.estatenest.ca are the exclusive property of Estate Nest Inc. and are protected under Canadian and international copyright and trademark laws.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">8. Strict Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by applicable Canadian law, Estate Nest Inc., its directors, officers, employees, and agents shall not be held liable for any direct, indirect, incidental, special, consequential, or punitive damages. This includes, but is not limited to, losses arising from software system downtimes, server data corruptions, data breaches beyond our technological control, underwriting delays, or your reliance on automated site content.
              </p>
              <p className="mt-4">
                Our professional Errors & Omissions (E&O) liability insurance coverage satisfies all provincial regulatory requirements under the AIC and FSRA, providing structural protection against professional negligence, but does not extend indemnity to external digital infrastructure failures.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">9. Dual-Jurisdictional Governing Law & Severability</h2>
              <p>
                These Terms and Conditions shall be governed by, construed, and enforced in accordance with the laws of the Province of Alberta, Canada, and the federal laws of Canada applicable therein. Any legal action, dispute, or lawsuit arising from the use of our services must be filed exclusively within the courts of Edmonton, Alberta.
              </p>
              <p className="mt-4">
                If any provision of these terms is deemed unlawful, void, or for any reason unenforceable by a court of competent jurisdiction, that specific provision shall be deemed severable and shall not affect the validity and enforceability of the remaining provisions.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">10. Contact Information</h2>
              <div className="mt-4 p-4 bg-muted rounded-lg">
                <p className="font-semibold text-foreground">Estate Nest Inc.</p>
                <p>Email: hello@estatenest.ca</p>
                <p>Phone: 780-860-3191</p>
                <p>Website: www.estatenest.ca</p>
              </div>
            </section>
          </div>
        </div>
      </div>

      <Footer />
    </div>
  );
};

export default Terms;

